"""empty message

Revision ID: 13232c2d3559
Revises: 9c74bea981fb
Create Date: 2020-05-22 11:58:43.022359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13232c2d3559'
down_revision = '9c74bea981fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_taker_id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['course_taker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subsection_id'], ['sub_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homework_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_taker_id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_taker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subsection_id'], ['sub_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_submissions')
    op.drop_table('homework_evaluations')
    # ### end Alembic commands ###
