"""empty message

Revision ID: 5fe88def1a02
Revises: 66a26e70a46e
Create Date: 2020-05-22 14:12:32.758182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe88def1a02'
down_revision = '66a26e70a46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'filename')
    # ### end Alembic commands ###
