"""empty message

Revision ID: 66a26e70a46e
Revises: 13232c2d3559
Create Date: 2020-05-22 12:27:37.772596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a26e70a46e'
down_revision = '13232c2d3559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_evaluations', sa.Column('filename', sa.String(length=100), nullable=True))
    op.add_column('homework_submissions', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework_submissions', 'filename')
    op.drop_column('homework_evaluations', 'filename')
    # ### end Alembic commands ###
