"""empty message

Revision ID: 9c74bea981fb
Revises: 8ff401d1ce8b
Create Date: 2020-05-20 13:43:09.183222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c74bea981fb'
down_revision = '8ff401d1ce8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['subsection_id'], ['sub_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    # ### end Alembic commands ###
