"""empty message

Revision ID: fcf983ebf792
Revises: b7cea8bc256d
Create Date: 2020-05-19 12:07:20.694727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf983ebf792'
down_revision = 'b7cea8bc256d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_taker_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_taker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_requests')
    # ### end Alembic commands ###
